"""Database access. SQLite locally; Postgres (Supabase) when DATABASE_URL is set."""

from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "data" / "ratings.db"
SOURCES_DIR = ROOT / "sources"

SPORT_TABLES = (
    "teams",
    "games",
    "group_teams",
    "season_rows",
    "standings",
    "projections",
    "our_games",
    "last_week",
    "sport_hfa",
    "line_matches",
)

PG_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS sports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        source_path TEXT,
        as_of TEXT,
        imported_at TEXT,
        file_mtime TEXT,
        watch INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS meta (
        key TEXT PRIMARY KEY,
        value TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS teams (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        rank INTEGER,
        rating DOUBLE PRECISION,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        change DOUBLE PRECISION,
        prev DOUBLE PRECISION,
        games DOUBLE PRECISION,
        n DOUBLE PRECISION,
        last_game TEXT,
        PRIMARY KEY (sport_id, name)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS games (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        date TEXT,
        team1 TEXT NOT NULL,
        score1 INTEGER NOT NULL,
        team2 TEXT NOT NULL,
        score2 INTEGER NOT NULL,
        home INTEGER,
        ori_off1 DOUBLE PRECISION,
        ori_def1 DOUBLE PRECISION,
        ori_off2 DOUBLE PRECISION,
        ori_def2 DOUBLE PRECISION,
        new_off1 DOUBLE PRECISION,
        new_def1 DOUBLE PRECISION,
        new_off2 DOUBLE PRECISION,
        new_def2 DOUBLE PRECISION,
        gd DOUBLE PRECISION,
        error DOUBLE PRECISION,
        course_par DOUBLE PRECISION
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_games_sport_date ON games(sport_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_games_sport_t1 ON games(sport_id, team1)",
    "CREATE INDEX IF NOT EXISTS idx_games_sport_t2 ON games(sport_id, team2)",
    """
    CREATE TABLE IF NOT EXISTS group_teams (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        group_key TEXT NOT NULL,
        team TEXT NOT NULL,
        rank INTEGER,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        rating DOUBLE PRECISION,
        PRIMARY KEY (sport_id, group_key, team)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS season_rows (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        team TEXT NOT NULL,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        w INTEGER,
        d INTEGER,
        grp INTEGER,
        pts INTEGER,
        spread DOUBLE PRECISION,
        odds DOUBLE PRECISION,
        adjp DOUBLE PRECISION,
        dist INTEGER,
        PRIMARY KEY (sport_id, team)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS standings (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        team TEXT NOT NULL,
        w INTEGER,
        d INTEGER,
        l INTEGER,
        pts INTEGER,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        gf INTEGER,
        ga INTEGER,
        gd INTEGER,
        PRIMARY KEY (sport_id, team)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS projections (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        team TEXT NOT NULL,
        quality DOUBLE PRECISION,
        pp DOUBLE PRECISION,
        qual_diff DOUBLE PRECISION,
        win_odds DOUBLE PRECISION,
        exp_pp DOUBLE PRECISION,
        notes TEXT,
        PRIMARY KEY (sport_id, team)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS our_games (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        game TEXT,
        date TEXT,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        rating DOUBLE PRECISION,
        running DOUBLE PRECISION
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS last_week (
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        team TEXT NOT NULL,
        rank INTEGER,
        rating DOUBLE PRECISION,
        off DOUBLE PRECISION,
        def DOUBLE PRECISION,
        change DOUBLE PRECISION,
        prev DOUBLE PRECISION,
        n DOUBLE PRECISION,
        last_game TEXT,
        PRIMARY KEY (sport_id, team)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sport_hfa (
        sport_id BIGINT PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
        q_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
        q_n DOUBLE PRECISION NOT NULL DEFAULT 100,
        r_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
        r_n DOUBLE PRECISION NOT NULL DEFAULT 100,
        season_key TEXT,
        updated_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS line_matches (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
        date TEXT,
        home_team TEXT NOT NULL,
        away_team TEXT NOT NULL,
        home INTEGER,
        s1s_h DOUBLE PRECISION, s1s_a DOUBLE PRECISION,
        s2s_h DOUBLE PRECISION, s2s_a DOUBLE PRECISION,
        s3s_h DOUBLE PRECISION, s3s_a DOUBLE PRECISION,
        s1d_h DOUBLE PRECISION, s1d_a DOUBLE PRECISION,
        s2d_h DOUBLE PRECISION, s2d_a DOUBLE PRECISION
    )
    """,
]


def _load_dotenv() -> None:
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv()


def get_database_url() -> str | None:
    url = os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL")
    if not url:
        return None
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://") :]
    # Render is IPv4; Supabase transaction pooler (6543) is a poor fit for
    # a long-running web process. Session pooler uses 5432 on the same host.
    if os.environ.get("DATABASE_POOL_MODE") != "transaction" and ":6543/" in url:
        url = url.replace(":6543/", ":5432/")
    if "sslmode=" not in url and "supabase" in url:
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


class Conn:
    def __init__(self, raw: Any, dialect: str):
        self._raw = raw
        self.dialect = dialect

    def _adapt(self, sql: str) -> str:
        if self.dialect == "postgres":
            return sql.replace("?", "%s")
        return sql

    def execute(self, sql: str, params: Any = None):
        sql = self._adapt(sql)
        if params is None:
            cur = self._raw.execute(sql)
        else:
            cur = self._raw.execute(sql, tuple(params))
        return Cursor(cur)

    def executemany(self, sql: str, seq) -> None:
        sql = self._adapt(sql)
        rows = list(seq)
        if not rows:
            return
        if self.dialect == "postgres":
            with self._raw.cursor() as cur:
                cur.executemany(sql, rows)
            return
        self._raw.executemany(sql, rows)

    def executescript(self, script: str) -> None:
        if self.dialect == "postgres":
            for stmt in script.split(";"):
                stmt = stmt.strip()
                if stmt:
                    self._raw.execute(stmt)
            return
        self._raw.executescript(script)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        try:
            self._raw.rollback()
        except Exception:
            pass

    def close(self) -> None:
        self._raw.close()


class Cursor:
    def __init__(self, cur: Any):
        self._cur = cur
        self.lastrowid = getattr(cur, "lastrowid", None)

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()


def _sqlite_row(cursor, row):
    return {col[0]: row[i] for i, col in enumerate(cursor.description)}


def connect(db_path: Path | None = None) -> Conn:
    url = get_database_url()
    if url and db_path is None:
        return connect_postgres(url)
    return connect_sqlite(db_path)


def connect_sqlite(db_path: Path | None = None) -> Conn:
    path = db_path or DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    SOURCES_DIR.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(str(path), timeout=60)
    raw.row_factory = _sqlite_row
    raw.execute("PRAGMA foreign_keys = ON")
    raw.execute("PRAGMA journal_mode = WAL")
    return Conn(raw, "sqlite")


def connect_postgres(url: str | None = None) -> Conn:
    import psycopg
    from psycopg.rows import dict_row

    dsn = url or get_database_url()
    if not dsn:
        raise RuntimeError("DATABASE_URL is not set")
    SOURCES_DIR.mkdir(parents=True, exist_ok=True)
    raw = psycopg.connect(
        dsn,
        row_factory=dict_row,
        prepare_threshold=None,
        connect_timeout=10,
        keepalives=1,
        keepalives_idle=30,
        keepalives_interval=10,
        keepalives_count=3,
    )
    return Conn(raw, "postgres")


def _tables(conn: Conn) -> set[str]:
    if conn.dialect == "postgres":
        rows = conn.execute(
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
        ).fetchall()
        return {r["tablename"] for r in rows}
    return {
        r["name"]
        for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()
    }


def _cols(conn: Conn, table: str) -> set[str]:
    if conn.dialect == "postgres":
        rows = conn.execute(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            """,
            (table,),
        ).fetchall()
        return {r["column_name"] for r in rows}
    rows = conn._raw.execute(f"PRAGMA table_info({table})").fetchall()
    return {r["name"] for r in rows}


def init_db(conn: Conn) -> None:
    if conn.dialect == "postgres":
        for stmt in PG_SCHEMA:
            conn.execute(stmt)
        conn.commit()
        return

    tables = _tables(conn)
    if "teams" in tables and "sports" not in tables:
        _migrate_legacy(conn)
    elif "teams" in tables and "sport_id" not in _cols(conn, "teams"):
        _migrate_legacy(conn)

    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS sports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            slug TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            source_path TEXT,
            as_of TEXT,
            imported_at TEXT,
            file_mtime TEXT,
            watch INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS meta (
            key TEXT PRIMARY KEY,
            value TEXT
        );

        CREATE TABLE IF NOT EXISTS teams (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            rank INTEGER,
            rating REAL,
            off REAL,
            def REAL,
            change REAL,
            prev REAL,
            games REAL,
            n INTEGER,
            last_game TEXT,
            PRIMARY KEY (sport_id, name)
        );

        CREATE TABLE IF NOT EXISTS games (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            date TEXT,
            team1 TEXT NOT NULL,
            score1 INTEGER NOT NULL,
            team2 TEXT NOT NULL,
            score2 INTEGER NOT NULL,
            home INTEGER,
            ori_off1 REAL,
            ori_def1 REAL,
            ori_off2 REAL,
            ori_def2 REAL,
            new_off1 REAL,
            new_def1 REAL,
            new_off2 REAL,
            new_def2 REAL,
            gd REAL,
            error REAL,
            course_par REAL
        );

        CREATE INDEX IF NOT EXISTS idx_games_sport_date ON games(sport_id, date);
        CREATE INDEX IF NOT EXISTS idx_games_sport_t1 ON games(sport_id, team1);
        CREATE INDEX IF NOT EXISTS idx_games_sport_t2 ON games(sport_id, team2);

        CREATE TABLE IF NOT EXISTS group_teams (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            group_key TEXT NOT NULL,
            team TEXT NOT NULL,
            rank INTEGER,
            off REAL,
            def REAL,
            rating REAL,
            PRIMARY KEY (sport_id, group_key, team)
        );

        CREATE TABLE IF NOT EXISTS season_rows (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            team TEXT NOT NULL,
            off REAL,
            def REAL,
            w INTEGER,
            d INTEGER,
            grp INTEGER,
            pts INTEGER,
            spread REAL,
            odds REAL,
            adjp REAL,
            dist INTEGER,
            PRIMARY KEY (sport_id, team)
        );

        CREATE TABLE IF NOT EXISTS standings (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            team TEXT NOT NULL,
            w INTEGER,
            d INTEGER,
            l INTEGER,
            pts INTEGER,
            off REAL,
            def REAL,
            gf INTEGER,
            ga INTEGER,
            gd INTEGER,
            PRIMARY KEY (sport_id, team)
        );

        CREATE TABLE IF NOT EXISTS projections (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            team TEXT NOT NULL,
            quality REAL,
            pp REAL,
            qual_diff REAL,
            win_odds REAL,
            exp_pp REAL,
            notes TEXT,
            PRIMARY KEY (sport_id, team)
        );

        CREATE TABLE IF NOT EXISTS our_games (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            game TEXT,
            date TEXT,
            off REAL,
            def REAL,
            rating REAL,
            running REAL
        );

        CREATE TABLE IF NOT EXISTS last_week (
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            team TEXT NOT NULL,
            rank INTEGER,
            rating REAL,
            off REAL,
            def REAL,
            change REAL,
            prev REAL,
            n INTEGER,
            last_game TEXT,
            PRIMARY KEY (sport_id, team)
        );

        CREATE TABLE IF NOT EXISTS sport_hfa (
            sport_id INTEGER PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
            q_sum REAL NOT NULL DEFAULT 0,
            q_n REAL NOT NULL DEFAULT 100,
            r_sum REAL NOT NULL DEFAULT 0,
            r_n REAL NOT NULL DEFAULT 100,
            season_key TEXT,
            updated_at TEXT
        );
        """
    )
    conn.commit()


def _migrate_legacy(conn: Conn) -> None:
    """Move the original single-sport tables under NJ Boys Soccer."""
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS sports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            slug TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            source_path TEXT,
            as_of TEXT,
            imported_at TEXT,
            file_mtime TEXT,
            watch INTEGER NOT NULL DEFAULT 1
        );
        """
    )
    existing = conn.execute("SELECT id FROM sports WHERE slug = 'nj-boys-soccer'").fetchone()
    if existing:
        sport_id = existing["id"]
    else:
        as_of = get_meta(conn, "as_of")
        imported_at = get_meta(conn, "imported_at")
        source = get_meta(conn, "source")
        row = conn.execute(
            """
            INSERT INTO sports(slug, name, source_path, as_of, imported_at, watch)
            VALUES (?, ?, ?, ?, ?, 1)
            RETURNING id
            """,
            (
                "nj-boys-soccer",
                "NJ Boys Soccer",
                source,
                as_of,
                imported_at,
            ),
        ).fetchone()
        sport_id = row["id"]

    if "sport_id" not in _cols(conn, "teams"):
        conn.executescript(
            f"""
            ALTER TABLE teams RENAME TO teams_legacy;
            CREATE TABLE teams (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                rank INTEGER,
                rating REAL,
                off REAL,
                def REAL,
                change REAL,
                prev REAL,
                games REAL,
                n INTEGER,
                last_game TEXT,
                PRIMARY KEY (sport_id, name)
            );
            INSERT INTO teams
            SELECT {sport_id}, name, rank, rating, off, def, change, prev, games, n, last_game
            FROM teams_legacy;
            DROP TABLE teams_legacy;
            """
        )

    def _add_sport_pk(table: str, create_sql: str, insert_sql: str) -> None:
        if table not in _tables(conn):
            return
        if "sport_id" in _cols(conn, table):
            return
        conn.execute(f"ALTER TABLE {table} RENAME TO {table}_legacy")
        conn.executescript(create_sql)
        conn.execute(insert_sql)
        conn.execute(f"DROP TABLE {table}_legacy")

    _add_sport_pk(
        "games",
        f"""
        CREATE TABLE games (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            date TEXT,
            team1 TEXT NOT NULL,
            score1 INTEGER NOT NULL,
            team2 TEXT NOT NULL,
            score2 INTEGER NOT NULL,
            home INTEGER,
            ori_off1 REAL, ori_def1 REAL, ori_off2 REAL, ori_def2 REAL,
            new_off1 REAL, new_def1 REAL, new_off2 REAL, new_def2 REAL,
            gd REAL, error REAL
        );
        """,
        f"""
        INSERT INTO games(
            sport_id, date, team1, score1, team2, score2, home,
            ori_off1, ori_def1, ori_off2, ori_def2,
            new_off1, new_def1, new_off2, new_def2, gd, error
        )
        SELECT {sport_id}, date, team1, score1, team2, score2, home,
            ori_off1, ori_def1, ori_off2, ori_def2,
            new_off1, new_def1, new_off2, new_def2, gd, error
        FROM games_legacy
        """,
    )

    for table, create, insert in [
        (
            "group_teams",
            f"""
            CREATE TABLE group_teams (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                group_key TEXT NOT NULL,
                team TEXT NOT NULL,
                rank INTEGER, off REAL, def REAL, rating REAL,
                PRIMARY KEY (sport_id, group_key, team)
            );
            """,
            f"""
            INSERT INTO group_teams
            SELECT {sport_id}, group_key, team, rank, off, def, rating FROM group_teams_legacy
            """,
        ),
        (
            "season_rows",
            f"""
            CREATE TABLE season_rows (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                team TEXT NOT NULL,
                off REAL, def REAL, w INTEGER, d INTEGER, grp INTEGER,
                pts INTEGER, spread REAL, odds REAL, adjp REAL, dist INTEGER,
                PRIMARY KEY (sport_id, team)
            );
            """,
            f"""
            INSERT INTO season_rows
            SELECT {sport_id}, team, off, def, w, d, grp, pts, spread, odds, adjp, dist
            FROM season_rows_legacy
            """,
        ),
        (
            "standings",
            f"""
            CREATE TABLE standings (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                team TEXT NOT NULL,
                w INTEGER, d INTEGER, l INTEGER, pts INTEGER,
                off REAL, def REAL, gf INTEGER, ga INTEGER, gd INTEGER,
                PRIMARY KEY (sport_id, team)
            );
            """,
            f"""
            INSERT INTO standings
            SELECT {sport_id}, team, w, d, l, pts, off, def, gf, ga, gd FROM standings_legacy
            """,
        ),
        (
            "projections",
            f"""
            CREATE TABLE projections (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                team TEXT NOT NULL,
                quality REAL, pp REAL, qual_diff REAL, win_odds REAL, exp_pp REAL, notes TEXT,
                PRIMARY KEY (sport_id, team)
            );
            """,
            f"""
            INSERT INTO projections
            SELECT {sport_id}, team, quality, pp, qual_diff, win_odds, exp_pp, notes
            FROM projections_legacy
            """,
        ),
        (
            "last_week",
            f"""
            CREATE TABLE last_week (
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                team TEXT NOT NULL,
                rank INTEGER, rating REAL, off REAL, def REAL,
                change REAL, prev REAL, n INTEGER, last_game TEXT,
                PRIMARY KEY (sport_id, team)
            );
            """,
            f"""
            INSERT INTO last_week
            SELECT {sport_id}, team, rank, rating, off, def, change, prev, n, last_game
            FROM last_week_legacy
            """,
        ),
    ]:
        _add_sport_pk(table, create, insert)

    if "our_games" in _tables(conn) and "sport_id" not in _cols(conn, "our_games"):
        conn.executescript(
            f"""
            ALTER TABLE our_games RENAME TO our_games_legacy;
            CREATE TABLE our_games (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                game TEXT, date TEXT, off REAL, def REAL, rating REAL, running REAL
            );
            INSERT INTO our_games(sport_id, game, date, off, def, rating, running)
            SELECT {sport_id}, game, date, off, def, rating, running FROM our_games_legacy;
            DROP TABLE our_games_legacy;
            """
        )

    conn.commit()


def set_meta(conn: Conn, key: str, value: str) -> None:
    conn.execute(
        "INSERT INTO meta(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )


def get_meta(conn: Conn, key: str, default: str | None = None) -> str | None:
    row = conn.execute("SELECT value FROM meta WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def get_sport(conn: Conn, slug: str):
    return conn.execute("SELECT * FROM sports WHERE slug = ?", (slug,)).fetchone()


def require_sport(conn: Conn, slug: str):
    row = get_sport(conn, slug)
    if not row:
        raise KeyError(slug)
    return row


def ensure_schema_extras(conn: Conn) -> None:
    """Create optional tables/columns used by the native engine (idempotent)."""
    if conn.dialect == "postgres":
        stmts = [
            """
            CREATE TABLE IF NOT EXISTS sport_hfa (
                sport_id BIGINT PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
                q_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
                q_n DOUBLE PRECISION NOT NULL DEFAULT 100,
                r_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
                r_n DOUBLE PRECISION NOT NULL DEFAULT 100,
                season_key TEXT,
                updated_at TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS line_matches (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                date TEXT,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                home INTEGER,
                s1s_h DOUBLE PRECISION, s1s_a DOUBLE PRECISION,
                s2s_h DOUBLE PRECISION, s2s_a DOUBLE PRECISION,
                s3s_h DOUBLE PRECISION, s3s_a DOUBLE PRECISION,
                s1d_h DOUBLE PRECISION, s1d_a DOUBLE PRECISION,
                s2d_h DOUBLE PRECISION, s2d_a DOUBLE PRECISION
            )
            """,
        ]
        for stmt in stmts:
            conn.execute(stmt)
        # Add course_par if missing (older DBs)
        cols = _cols(conn, "games")
        if "course_par" not in cols:
            conn.execute("ALTER TABLE games ADD COLUMN course_par DOUBLE PRECISION")
        conn.commit()
        return

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS sport_hfa (
            sport_id INTEGER PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
            q_sum REAL NOT NULL DEFAULT 0,
            q_n REAL NOT NULL DEFAULT 100,
            r_sum REAL NOT NULL DEFAULT 0,
            r_n REAL NOT NULL DEFAULT 100,
            season_key TEXT,
            updated_at TEXT
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS line_matches (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
            date TEXT,
            home_team TEXT NOT NULL,
            away_team TEXT NOT NULL,
            home INTEGER,
            s1s_h REAL, s1s_a REAL,
            s2s_h REAL, s2s_a REAL,
            s3s_h REAL, s3s_a REAL,
            s1d_h REAL, s1d_a REAL,
            s2d_h REAL, s2d_a REAL
        )
        """
    )
    cols = _cols(conn, "games") if "games" in _tables(conn) else set()
    if cols and "course_par" not in cols:
        conn.execute("ALTER TABLE games ADD COLUMN course_par REAL")
    conn.commit()


def clear_sport_data(conn: Conn, sport_id: int) -> None:
    existing = _tables(conn)
    for table in SPORT_TABLES:
        if table not in existing:
            continue
        conn.execute(f"DELETE FROM {table} WHERE sport_id = ?", (sport_id,))
