"""Replay game logs through the native rating engine and write teams/games."""

from __future__ import annotations

from datetime import datetime, timezone

from catalog import SPORTS, sport_by_slug
from db import DB_PATH, connect, connect_sqlite, init_db, set_meta
from rating_engine import (
    EngineState,
    HfaState,
    HFA_REBUILD_N,
    ranked_rows,
)


def _utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ensure_tables(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sport_hfa (
                sport_id BIGINT PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
                q_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
                q_n DOUBLE PRECISION NOT NULL DEFAULT 100,
                r_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
                r_n DOUBLE PRECISION NOT NULL DEFAULT 100,
                season_key TEXT,
                updated_at TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS line_matches (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sport_id BIGINT NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                date TEXT,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                home INTEGER,
                s1s_h DOUBLE PRECISION, s1s_a DOUBLE PRECISION,
                s2s_h DOUBLE PRECISION, s2s_a DOUBLE PRECISION,
                s3s_h DOUBLE PRECISION, s3s_a DOUBLE PRECISION,
                s1d_h DOUBLE PRECISION, s1d_a DOUBLE PRECISION,
                s2d_h DOUBLE PRECISION, s2d_a DOUBLE PRECISION
            )
            """
        )
    else:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sport_hfa (
                sport_id INTEGER PRIMARY KEY REFERENCES sports(id) ON DELETE CASCADE,
                q_sum REAL NOT NULL DEFAULT 0,
                q_n REAL NOT NULL DEFAULT 100,
                r_sum REAL NOT NULL DEFAULT 0,
                r_n REAL NOT NULL DEFAULT 100,
                season_key TEXT,
                updated_at TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS line_matches (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sport_id INTEGER NOT NULL REFERENCES sports(id) ON DELETE CASCADE,
                date TEXT,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                home INTEGER,
                s1s_h REAL, s1s_a REAL,
                s2s_h REAL, s2s_a REAL,
                s3s_h REAL, s3s_a REAL,
                s1d_h REAL, s1d_a REAL,
                s2d_h REAL, s2d_a REAL
            )
            """
        )
    # optional golf par column on games
    cols = {c for c in _cols(conn, "games")} if _table_exists(conn, "games") else set()
    if cols and "course_par" not in cols:
        try:
            conn.execute("ALTER TABLE games ADD COLUMN course_par DOUBLE PRECISION")
        except Exception:
            try:
                conn.execute("ALTER TABLE games ADD COLUMN course_par REAL")
            except Exception:
                pass
    conn.commit()


def _table_exists(conn, name: str) -> bool:
    if conn.dialect == "postgres":
        row = conn.execute(
            "SELECT 1 AS o FROM information_schema.tables WHERE table_name = ?",
            (name,),
        ).fetchone()
        return bool(row)
    row = conn.execute(
        "SELECT 1 AS o FROM sqlite_master WHERE type='table' AND name = ?",
        (name,),
    ).fetchone()
    return bool(row)


def _cols(conn, table: str) -> set[str]:
    if conn.dialect == "postgres":
        rows = conn.execute(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            """,
            (table,),
        ).fetchall()
        return {r["column_name"] for r in rows}
    rows = conn._raw.execute(f"PRAGMA table_info({table})").fetchall()
    return {r["name"] for r in rows}


def _norm_date(d: str | None) -> str | None:
    if not d:
        return d
    s = str(d).strip()
    if len(s) >= 10 and s[4] == "-" and s[7] == "-":
        return s[:10]
    # M/D/YYYY
    parts = s.replace("-", "/").split("/")
    if len(parts) == 3:
        try:
            m, d0, y = int(parts[0]), int(parts[1]), int(parts[2])
            if y < 100:
                y += 2000
            return f"{y:04d}-{m:02d}-{d0:02d}"
        except ValueError:
            return s
    return s


def recompute_sport(
    slug: str,
    *,
    write_game_ratings: bool = True,
    hfa_start_n: float = HFA_REBUILD_N,
    use_sqlite: bool = False,
) -> dict:
    """Chronologically replay all games for a sport through the native engine."""
    spec = sport_by_slug(slug)
    if not spec:
        raise ValueError(f"Unknown sport: {slug}")

    engine_name = spec.get("engine") or "offdef"
    games_delta = float(spec.get("games_delta") or 0.75)
    group = spec.get("group") or "Fall"

    conn = connect_sqlite(DB_PATH) if use_sqlite else connect()
    init_db(conn)
    _ensure_tables(conn)
    try:
        sport = conn.execute("SELECT * FROM sports WHERE slug = ?", (slug,)).fetchone()
        if not sport:
            raise ValueError(f"Sport not in DB (import games first): {slug}")
        sport_id = sport["id"]

        engine = EngineState(
            hfa=HfaState(q_sum=0.0, q_n=hfa_start_n, r_sum=0.0, r_n=hfa_start_n),
            auto_seed_new=True,
            engine=engine_name if engine_name != "lines" else "lines",
            games_delta=games_delta,
        )
        last_by_team: dict[str, str | None] = {}
        updates = []
        seeded = 0
        duals = 0

        if engine_name == "lines":
            matches = conn.execute(
                """
                SELECT * FROM line_matches
                WHERE sport_id = ?
                ORDER BY date ASC, id ASC
                """,
                (sport_id,),
            ).fetchall()
            if not matches:
                raise ValueError(f"No tennis line_matches for {slug} — re-import from Drive first")
            for m in matches:
                date = _norm_date(m["date"])
                scores = {}
                mapping = [
                    ("1S", "s1s_h", "s1s_a"),
                    ("2S", "s2s_h", "s2s_a"),
                    ("3S", "s3s_h", "s3s_a"),
                    ("1D", "s1d_h", "s1d_a"),
                    ("2D", "s2d_h", "s2d_a"),
                ]
                for pos, hcol, acol in mapping:
                    hv, av = m[hcol], m[acol]
                    if hv is not None and av is not None:
                        scores[pos] = (float(hv), float(av))
                engine.process_tennis_dual(
                    date,
                    m["home_team"],
                    m["away_team"],
                    bool(m["home"]),
                    scores,
                    group=group,
                )
                duals += 1
                last_by_team[engine.display_name(m["home_team"])] = date
                last_by_team[engine.display_name(m["away_team"])] = date
            game_count = duals
        else:
            has_par = "course_par" in _cols(conn, "games")
            select = """
                SELECT id, date, team1, score1, team2, score2, home,
                       ori_off1, ori_def1, ori_off2, ori_def2,
                       new_off1, new_def1, new_off2, new_def2
            """
            if has_par:
                select += ", course_par"
            select += " FROM games WHERE sport_id = ? ORDER BY date ASC, id ASC"
            games = conn.execute(select, (sport_id,)).fetchall()
            if not games:
                raise ValueError(f"No games for {slug}")

            for g in games:
                date = _norm_date(g["date"])
                # Fix sort key issues with non-ISO dates by using normalized
                par = g["course_par"] if has_par else None
                result = engine.process_game(
                    date,
                    g["team1"],
                    g["score1"],
                    g["team2"],
                    g["score2"],
                    bool(g["home"]),
                    group=group,
                    course_par=par,
                )
                if result.seeded1 or result.seeded2:
                    seeded += 1
                last_by_team[engine.display_name(g["team1"])] = date
                last_by_team[engine.display_name(g["team2"])] = date
                if write_game_ratings:
                    updates.append(
                        (
                            result.ori_off1,
                            result.ori_def1,
                            result.ori_off2,
                            result.ori_def2,
                            result.new_off1,
                            result.new_def1,
                            result.new_off2,
                            result.new_def2,
                            result.gd,
                            result.error,
                            g["id"],
                        )
                    )

            if write_game_ratings and updates:
                conn.executemany(
                    """
                    UPDATE games SET
                      ori_off1=?, ori_def1=?, ori_off2=?, ori_def2=?,
                      new_off1=?, new_def1=?, new_off2=?, new_def2=?,
                      gd=?, error=?
                    WHERE id=?
                    """,
                    updates,
                )
            game_count = len(games)

        rows = ranked_rows(
            engine.teams,
            canonical=engine.canonical,
            active_only=True,
            games_delta=games_delta,
        )
        for r in rows:
            r["last_game"] = last_by_team.get(r["name"])

        prior = {
            r["name"]: r
            for r in conn.execute(
                "SELECT name, change, prev FROM teams WHERE sport_id = ?",
                (sport_id,),
            ).fetchall()
        }
        prior_l = {k.lower(): v for k, v in prior.items()}
        conn.execute("DELETE FROM teams WHERE sport_id = ?", (sport_id,))
        batch = []
        for r in rows:
            old = prior.get(r["name"]) or prior_l.get(r["name"].lower(), {})
            off = r["off"]
            deff = r["def"]
            # single-rating: store rating in off, leave def null
            if engine_name not in ("offdef",) and deff is None:
                off = r["rating"]
            batch.append(
                (
                    sport_id,
                    r["name"],
                    r["rank"],
                    r["rating"],
                    off,
                    deff,
                    old.get("change") if isinstance(old, dict) else None,
                    old.get("prev") if isinstance(old, dict) else None,
                    r["games"],
                    r["n"],
                    r.get("last_game"),
                )
            )
        conn.executemany(
            """
            INSERT INTO teams(sport_id, name, rank, rating, off, def, change, prev, games, n, last_game)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            batch,
        )

        conn.execute(
            """
            INSERT INTO sport_hfa(sport_id, q_sum, q_n, r_sum, r_n, season_key, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(sport_id) DO UPDATE SET
              q_sum=excluded.q_sum, q_n=excluded.q_n,
              r_sum=excluded.r_sum, r_n=excluded.r_n,
              season_key=excluded.season_key, updated_at=excluded.updated_at
            """,
            (
                sport_id,
                engine.hfa.q_sum,
                engine.hfa.q_n,
                engine.hfa.r_sum,
                engine.hfa.r_n,
                engine.current_season,
                _utcnow(),
            ),
        )
        set_meta(conn, f"recompute_{slug}_at", _utcnow())
        set_meta(conn, "rankings_source", "native_engine")
        conn.commit()

        return {
            "ok": True,
            "slug": slug,
            "engine": engine_name,
            "games": game_count,
            "teams": len(rows),
            "seeded_appearances": seeded,
            "season": engine.current_season,
            "hfa": {
                "q4": round(engine.hfa.q4, 6),
                "r4": round(engine.hfa.r4, 6),
                "q_n": engine.hfa.q_n,
                "r_n": engine.hfa.r_n,
            },
            "top5": [
                {"rank": r["rank"], "name": r["name"], "rating": round(r["rating"], 4)}
                for r in rows[:5]
            ],
            "source": "native_engine",
        }
    finally:
        conn.close()


def recompute_all(**kwargs) -> list[dict]:
    results = []
    for spec in SPORTS:
        try:
            results.append(recompute_sport(spec["slug"], **kwargs))
        except Exception as exc:
            results.append({"ok": False, "slug": spec["slug"], "error": str(exc)})
    return results


def recompute_all_offdef(**kwargs) -> list[dict]:
    """Backward-compatible: recompute every sport the engine supports."""
    return recompute_all(**kwargs)


if __name__ == "__main__":
    import argparse
    import json

    parser = argparse.ArgumentParser(description="Recompute ratings from game logs")
    parser.add_argument("--slug")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--all-offdef", action="store_true")
    parser.add_argument("--sqlite", action="store_true")
    args = parser.parse_args()
    kw = {"use_sqlite": args.sqlite}
    if args.all or args.all_offdef:
        print(json.dumps(recompute_all(**kw), indent=2, default=str))
    elif args.slug:
        print(json.dumps(recompute_sport(args.slug, **kw), indent=2, default=str))
    else:
        parser.error("Pass --slug or --all")
